[features]
seeds = false
[programs.localnet]
mysolanaapp = "A8y98u143ADQCX8WE67KavQiTA9W35JKQjJF3bcHdgwy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/alex/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
